image: gitpod/workspace-full:2023-02-27-14-39-56
tasks:
  - name: scenario-setup
    before: |
      # THESE ARE EXAMPLE COMMANDS
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" | tee -a $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' | tee -a $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli" | bash | tee -a ./katapod_logs/astra-cli-install.log
    init: |
      # THESE ARE EXAMPLE COMMANDS
      pip install cassandra-driver==3.25
      ./scenario_scripts/setup-something.sh  | tee -a ./katapod_logs/setup-something.log
    command: |
      # THESE ARE EXAMPLE COMMANDS
      source /home/gitpod/.astra/cli/astra-init.sh
ports:
  # THIS IS AN EXAMPLE ENTRY
  - port: 8000
    onOpen: ignore
github:
  prebuilds:
    main: true
vscode:
   extensions:
    - https://github.com/DataStax-Academy/katapod/releases/download/stable/katapod-stable.vsix
