tasks:
  - name: install-dependencies
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli" | bash >> ./install.log
    init: |
      pip install -U cqlsh
    command: |
      source /home/gitpod/.astra/cli/astra-init.sh
github:
  prebuilds:
    main: true
vscode:
   extensions:
    - https://github.com/hemidactylus/katapod/releases/download/1.1.0-beta1/katapod-1.1.0-beta1.vsix

